version: "3.9"

services:
  frontend:
    image: vanhoadotbui2628/dental_frontend:1.0.0
    container_name: dental-frontend
    restart: unless-stopped
    depends_on:
      strapi:
        condition: service_healthy
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_SERVER_URL: https://nhakhoaquoctesaigon.ddns.net
      STRAPI_URL: http://13.210.111.152:1337
      STRAPI_API_TOKEN: 17d23dee39bfcd47d333c413e295deee0995354746a0043cd32eed8cadbcf796739ca2627a7f966ad4d6d01a4f3b741efcffab944ee56d9a4961c61c48c4b4746406092c04ccadd7267242d253d8e53597d4433bb481f858ebb651d239f86e5d58bc43eb20b4abbe85170494c046b353a922b65dac0b939485a5f56871edafa1
      NEXT_PREVIEW_SECRET: your-secure-preview-secret-change-in-production
    ports:
      - "3003:3000"
    networks:
      - dental-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000",
        ]
      interval: 30s
      timeout: 10s
      start_period: 40s
      retries: 3

networks:
  dental-network:
    driver: bridge
