module.exports = {
  apps: [
    {
      name: "dental-strapi",
      cwd: "/home/ec2-user/dental-app/strapi-cms",
      script: "./node_modules/.bin/strapi",
      args: "start",
      env: {
        NODE_ENV: "production",
        HOST: "0.0.0.0",
        PORT: 1337,
        DATABASE_CLIENT: "postgres",
        DATABASE_HOST: "localhost",
        DATABASE_PORT: 5433,
        DATABASE_NAME: "dental_cms_strapi",
        DATABASE_USERNAME: "postgres",
        DATABASE_PASSWORD: "postgres",
        DATABASE_SSL: "false",
        DATABASE_SCHEMA: "public",
        APP_KEYS:
          "1r05bMPHwD42mUYeOWRNTw==,0OklUtllewJlZhzHPcEs1A==,HYPHeVFKy21fbmYRkNXsng==,U6MGvCrIvYzwFc5BX+jC3g==",
        API_TOKEN_SALT: "HFBTyl5TbQh4LRyq68kY3A==",
        ADMIN_JWT_SECRET: "Ow3nHJBVT5378ti+xvpQQg==",
        TRANSFER_TOKEN_SALT: "x8Voe+7fNjUrTNinjMqfTg==",
        JWT_SECRET: "Ow3nHJBVT5378ti+xvpQQg==",
        PUBLIC_URL: "https://nhakhoaquoctesaigon.ddns.net",
        FRONTEND_URL: "https://nhakhoaquoctesaigon.ddns.net",
        PREVIEW_SECRET: "your-secure-preview-secret-change-in-production",
        STRAPI_WEBHOOK_SECRET:
          "dental-webhook-secret-2026-change-in-production",
        NEXTJS_URL: "https://nhakhoaquoctesaigon.ddns.net",
      },
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
    },
    {
      name: "dental-frontend",
      cwd: "/home/ec2-user/dental-app/dental-frontend",
      script: "./node_modules/.bin/next",
      args: "start -p 3003",
      env: {
        NODE_ENV: "production",
        PORT: 3003,
        NEXT_PUBLIC_SERVER_URL: "https://nhakhoaquoctesaigon.ddns.net",
        STRAPI_URL: "http://localhost:1337",
        STRAPI_API_TOKEN:
          "17d23dee39bfcd47d333c413e295deee0995354746a0043cd32eed8cadbcf796739ca2627a7f966ad4d6d01a4f3b741efcffab944ee56d9a4961c61c48c4b4746406092c04ccadd7267242d253d8e53597d4433bb481f858ebb651d239f86e5d58bc43eb20b4abbe85170494c046b353a922b65dac0b939485a5f56871edafa1",
        NEXT_PREVIEW_SECRET: "your-secure-preview-secret-change-in-production",
      },
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
    },
  ],
};
